apiVersion: v1
kind: Service
metadata:
  name: tracery-hub
  namespace: tracery
  labels:
    app.kubernetes.io/name: tracery-hub
spec:
  selector:
    app.kubernetes.io/name: tracery-hub
  ports:
    - name: http
      port: 8971
      targetPort: http
