{{- if and (not .Values.postgres.existingSecret) .Values.postgres.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracery-hub.postgresSecretName" . }}
  labels:
    {{- include "tracery-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.postgres.url | quote }}
{{- end }}
